const destinations: Record<string, string> = {
  "+603 7809 8833": "tel:+603 7809 8833",
  "Product Enquiry": "https://www.klkoleo.com/product-enquiry/",
  "en": "https://www.klkoleo.com/",
  "de": "https://www.klkoleo.com/de/",
  "cn": "https://www.klkoleo.com/cn/",
  "About Us": "https://www.klkoleo.com/company/klk-oleo-brief/",
  "KLK OLEO in Brief": "https://www.klkoleo.com/company/klk-oleo-brief/",
  "History & Milestones": "https://www.klkoleo.com/history-milestones/",
  "Sustainability Principled by Integrity": "https://www.klkoleo.com/sustainability-principled-by-integrity/",
  "Corporate Responsibility": "https://www.klkoleo.com/corporate-responsibility/",
  "Standard Terms and Conditions": "https://www.klkoleo.com/standard-terms-and-conditions/",
  "Supplier Code of Conduct": "https://www.klkoleo.com/supplier-code-of-conduct/",
  "Governance and Policies": "https://www.klkoleo.com/governance-and-policies/",
  "Amides": "https://www.klkoleo.com/products/amides/",
  "Anionic Surfactants": "https://www.klkoleo.com/products/anionic-surfactants/",
  "Fatty Esters": "https://www.klkoleo.com/products/esters/",
  "Esters": "https://www.klkoleo.com/products/esters/",
  "Fatty Acids": "https://www.klkoleo.com/products/fatty-acids/",
  "Fatty Alcohols": "https://www.klkoleo.com/products/fatty-alcohols/",
  "Glycerine": "https://www.klkoleo.com/products/glycerine/",
  "Nonionic Surfactants": "https://www.klkoleo.com/products/nonionic-surfactants/",
  "Phytonutrients": "https://www.klkoleo.com/products/phytonutrients/",
  "Accreditations": "https://www.klkoleo.com/accreditations/",
  "Beauty & Personal Care": "https://www.klkoleo.com/markets/beauty-personal-care/",
  "Food & Nutrition": "https://www.klkoleo.com/markets/food-nutrition/",
  "Home Care, Industries & Institutional (I&I) Cleaning": "https://www.klkoleo.com/markets/home-care-industries-institutional-ii-cleaning/",
  "Life Science": "https://www.klkoleo.com/lifescience/",
  "Lubricants": "https://www.klkoleo.com/markets/lubricants/",
  "Oleo Basics": "https://www.klkoleo.com/oleo-basics/",
  "Polymers": "https://www.klkoleo.com/markets/polymers/",
  "Careers": "https://www.klkoleo.com/careers/",
  "News & Media": "https://www.klkoleo.com/news-media/",
  "Contact Us": "https://www.klkoleo.com/contact-us/",
  "Kuala Lumpur Kepong Berhad": "http://www.klk.com.my",
  "Read More": "https://www.klkoleo.com/news-media/pchi-2026/",
  "Food Nutrition": "https://www.klkoleo.com/markets/food-nutrition/",
  "KLK EMMERICH GmbH": "https://www.klkoleo.com/klkemmerich/",
  "KLK Tensachem": "https://www.klkoleo.com/klktensachem/",
  "Kolb Distribution": "https://www.kolb.ch/",
  "KLK Kolb Specialties": "https://www.kolb.ch/company/#delden",
  "KSP Manufacturing": "https://www.klkoleo.com/ksp-manufacturing-sdn-bhd/",
  "Palmamide": "https://www.klkoleo.com/palmamide-sdn-bhd/",
  "Palm-Oleo": "https://www.klkoleo.com/palm-oleo-sdn-bhd/",
  "Palm-Oleo (Klang)": "https://www.klkoleo.com/palm-oleo-klang-sdn-bhd/",
  "KL-Kepong Oleomas": "https://www.klkoleo.com/kl-kepong-oleomas-sdn-bhd/",
  "KLK Bioenergy": "https://www.klkoleo.com/klk-bioenergy-sdn-bhd/",
  "DAVOS LIFE SCIENCE": "https://www.klkoleo.com/davoslife/",
  "Taiko Palm-Oleo (Zhangjiagang)": "https://www.klkoleo.com/taiko-palm-oleo-zhangjiagang-co-ltd/",
  "KLK Dumai": "https://www.klkoleo.com/pt-klk-dumai/",
  "Davos Life Science": "https://klkoleo.com/davoslife/",
  "Stolthaven (Westport)": "https://www.klkoleo.com/stolthavenwestport/",
  "Perindustrian Sawit Synergi": "https://www.klkoleo.com/ptperindustriansawitsynergi/",
  "KLK OLEO India": "https://www.klkoleo.com/klkoleo-india/",
  "Dr. W. Kolb Nederland": "https://www.kolb.ch/company/",
  "KLK Temix": "https://www.klkoleo.com/klktemix/",
  "KLK OLEO Americas": "https://www.klkoleo.com/klk-oleo-americas-inc/",
  "View More": "https://www.klkoleo.com/news-media",
  "Davos Life Science & ColorNet: Transforming Brazil\u2019s Skincare Future with the Power of Tocotrienols": "https://www.klkoleo.com/news-media/davos-life-science-colornet-transforming-brazils-skincare-future-with-the-power-of-tocotrienols/",
  "Visit KLK OLEO at in-cosmetics Latin America 2026": "https://www.klkoleo.com/news-media/visit-klk-oleo-at-in-cosmetics-latin-america-2026/",
  "Trusted Partner for Healthy Ageing and Healthier Living": "https://www.klkoleo.com/news-media/trusted-partner-for-healthy-ageing-and-healthier-living/",
  "Sustainable ingredients, touching lives positively, everyday": "https://www.klkoleo.com/news-media/sustainable-ingredients-touching-lives-positively-everyday/",
  "Celebrating 100 Years of Excellence in Delden": "https://www.klkoleo.com/news-media/celebrating-100-years-of-excellence-in-delden/",
  "Discover KLK OLEO\u2019s Science-Led Innovations at Vitafoods Europe 2026": "https://www.klkoleo.com/news-media/vitafoods-europe-2026/",
  "Discover innovative nature-derived products and solutions at ChemExpo India!": "https://www.klkoleo.com/news-media/discover-innovative-nature-derived-products-and-solutions-at-chemexpo-india/",
  "Discover KLK OLEO\u2019s Sustainable Personal Care and Home Care Solutions at PCHi": "https://www.klkoleo.com/news-media/pchi-2026/",
  "The Edge Billion Ringgit Club": "https://theedgemalaysia.com/node/689460",
  "Sustainability": "https://www.klkoleo.com/sustainability-principled-by-integrity/",
  "Disclaimer": "https://www.klkoleo.com/disclaimer/",
  "Personal Data Notice Statement": "https://www.klkoleo.com/privacy-policy/",
  "Privacy Notice": "https://www.klk.com.my/privacy-notice/",
  "Cookie Notice": "https://www.klkoleo.com/cookie-policy",
  "Linkedin": "https://www.linkedin.com/company/klkberhad/",
  "About Us\u25bc": "https://www.klkoleo.com/company/klk-oleo-brief/",
  "Sustainability\u25bc": "https://www.klkoleo.com/sustainability-principled-by-integrity/",
  "Customers and Suppliers\u25bc": "https://www.klkoleo.com/standard-terms-and-conditions/",
  "Contact Us\u25bc": "https://www.klkoleo.com/contact-us/",
  "Career": "https://www.klkoleo.com/careers/",
  "News & Events": "https://www.klkoleo.com/news-media/",
  "Personal Care": "https://www.klkoleo.com/markets/beauty-personal-care/",
  "Home Care": "https://www.klkoleo.com/markets/home-care-industries-institutional-ii-cleaning/",
  "Industrial Solutions": "https://www.klkoleo.com/markets/lubricants/",
  "Sustainable Solutions": "https://www.klkoleo.com/sustainability-principled-by-integrity/",
  "Global Supply": "https://www.klkoleo.com/contact-us/"
};

const prototypeDestinations: Record<string, string> = {
  "About Us": "/about-us",
  "KLK OLEO in Brief": "/about-us",
  "History & Milestones": "/history-milestones",
  "Sustainability": "/sustainability",
  "Corporate Responsibility": "/corporate-responsibility",
  "Career": "/careers",
  "Careers": "/careers",
  "Markets": "/markets",
  "Accreditations": "/accreditations",
  "Standard Terms and Conditions": "/standard-terms-and-conditions",
  "Supplier Code of Conduct": "/supplier-code-of-conduct",
  "Governance and Policies": "/governance-and-policies",
  "Disclaimer": "/disclaimer",
  "Personal Data Notice Statement": "/privacy-policy",
  "Privacy Notice": "/privacy-notice",
  "Cookie Notice": "/cookie-policy",
  "Products": "/products",
  "Fatty Acids": "/products/fatty-acids",
  "Product Enquiry": "/product-enquiry",
  "News & Events": "/news-events",
  "News & Media": "/news-events",
  "View More": "/news-events/archive",
  "Read More": "/news-events",
  "Contact Us": "/contact-us",
  "Global Supply": "/contact-us",
};
for (const category of ["Amides", "Anionic Surfactants", "Esters", "Fatty Esters", "Fatty Alcohols", "Glycerine", "Nonionic Surfactants", "Phytonutrients"]) {
  prototypeDestinations[category] = `/products/${category === "Fatty Esters" ? "esters" : category.toLowerCase().replaceAll(" ", "-")}`;
}

const marketRoutes: Record<string, string> = {
  "Beauty & Personal Care": "beauty-personal-care", "Personal Care": "beauty-personal-care",
  "Food & Nutrition": "food-nutrition", "Food Nutrition": "food-nutrition",
  "Home Care, Industries & Institutional (I&I) Cleaning": "home-care-industries-institutional-ii-cleaning", "Home Care": "home-care-industries-institutional-ii-cleaning",
  "Life Science": "life-science", "Lubricants": "lubricants", "Industrial Solutions": "lubricants", "Oleo Basics": "oleo-basics", "Polymers": "polymers",
};
for (const [market, slug] of Object.entries(marketRoutes)) {
  prototypeDestinations[market] = `/markets/${slug}`;
}

export function destinationFor(label: string) {
  const destination = prototypeDestinations[label] ?? destinations[label] ?? "/contact-us";
  if (destination.startsWith("https://www.klkoleo.com/news-media/")) return destination.replace("https://www.klkoleo.com/news-media/", "/news-events/");
  const profileSlugs = ["klkemmerich", "klktensachem", "ksp-manufacturing-sdn-bhd", "palmamide-sdn-bhd", "palm-oleo-sdn-bhd", "palm-oleo-klang-sdn-bhd", "kl-kepong-oleomas-sdn-bhd", "klk-bioenergy-sdn-bhd", "taiko-palm-oleo-zhangjiagang-co-ltd", "pt-klk-dumai", "stolthavenwestport", "ptperindustriansawitsynergi", "klkoleo-india", "klktemix", "klk-oleo-americas-inc"];
  const profile = profileSlugs.find(slug => destination === `https://www.klkoleo.com/${slug}/`);
  if (profile) return `/${profile}`;
  if (/^https:\/\/(www\.)?klkoleo\.com\/davoslife\/$/.test(destination)) return "/company/davos-life-science";
  return destination;
}
