/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    sites: Site;
    media: Media;
    'product-functions': ProductFunction;
    'formulation-types': FormulationType;
    'regulatory-labels': RegulatoryLabel;
    products: Product;
    pages: Page;
    banners: Banner;
    resources: Resource;
    'routing-profiles': RoutingProfile;
    forms: Form;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'product-functions': ProductFunctionsSelect<false> | ProductFunctionsSelect<true>;
    'formulation-types': FormulationTypesSelect<false> | FormulationTypesSelect<true>;
    'regulatory-labels': RegulatoryLabelsSelect<false> | RegulatoryLabelsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'routing-profiles': RoutingProfilesSelect<false> | RoutingProfilesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'super-admin' | 'site-admin' | 'editor' | 'publisher' | 'lead-manager' | 'viewer';
  sites?: (number | Site)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  slug: string;
  kind: 'main' | 'minisite';
  parentSite?: (number | null) | Site;
  domain: string;
  active?: boolean | null;
  market?: string | null;
  brandName?: string | null;
  parentLinkLabel?: string | null;
  navigation?:
    | {
        label: string;
        path: string;
        id?: string | null;
      }[]
    | null;
  contactEmail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  site: number | Site;
  alt: string;
  caption?: string | null;
  /**
   * Enable for approved public website images and downloads.
   */
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-functions".
 */
export interface ProductFunction {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  /**
   * Functions in agrochemical formulations.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formulation-types".
 */
export interface FormulationType {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  /**
   * Formulation technology or type.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulatory-labels".
 */
export interface RegulatoryLabel {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  /**
   * Source-reported label. Verification is required before publishing claims.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  chemicalDescription: string;
  description: string;
  functions?: (number | ProductFunction)[] | null;
  formulationTypes?: (number | FormulationType)[] | null;
  regulatoryLabels?: (number | RegulatoryLabel)[] | null;
  /**
   * Spreadsheet ticks are source claims, not independently validated certifications.
   */
  claimsReview: 'source-only' | 'verified' | 'needs-correction';
  /**
   * Source value retained, including mixtures and proprietary entries.
   */
  casNumber?: string | null;
  manufacturingRegion?: ('EU' | 'MY') | null;
  resources?: (number | Resource)[] | null;
  image?: (number | null) | Media;
  featured?: boolean | null;
  sourceNumber?: number | null;
  sourceRow?: number | null;
  /**
   * Original website or spreadsheet URL.
   */
  sourceURL?: string | null;
  /**
   * Reference filename only. No approved downloadable material exists yet.
   */
  sourceDocument?: string | null;
  sourceCells?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  site: number | Site;
  title: string;
  slug: string;
  description?: string | null;
  type: 'brochure' | 'technical-guide' | 'safety-data-sheet' | 'case-study';
  availability: 'placeholder' | 'available';
  placeholderLabel?: string | null;
  file?: (number | null) | Media;
  /**
   * Document cover image. Set its Media isPublic flag to display it on the website; this is independent of PDF download visibility.
   */
  thumbnail?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  site: number | Site;
  title: string;
  slug: string;
  template: 'home' | 'standard' | 'product-finder' | 'resource-library' | 'contact';
  hero?: {
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
    image?: (number | null) | Media;
  };
  sections?:
    | {
        heading?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Original website or spreadsheet URL.
   */
  sourceURL?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  site: number | Site;
  title: string;
  placement: string;
  headline: string;
  body?: string | null;
  desktopImage?: (number | null) | Media;
  mobileImage?: (number | null) | Media;
  ctaLabel?: string | null;
  ctaPath?: string | null;
  displayOrder?: number | null;
  /**
   * Original website or spreadsheet URL.
   */
  sourceURL?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routing-profiles".
 */
export interface RoutingProfile {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  purpose: 'general-enquiry' | 'product-enquiry' | 'sample-request' | 'technical-support';
  mode: 'manual' | 'crm';
  /**
   * Server-side adapter key; never put CRM credentials here.
   */
  connectorKey?: string | null;
  destinationTeam?: string | null;
  /**
   * Reserved for a versioned routing engine. Not executed in this initial release.
   */
  rules?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  site: number | Site;
  name: string;
  slug: string;
  purpose: 'general-enquiry' | 'product-enquiry' | 'sample-request' | 'technical-support';
  routingProfile: number | RoutingProfile;
  consentLabel: string;
  successMessage?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  site: number | Site;
  form: number | Form;
  purpose: string;
  email: string;
  firstName: string;
  lastName?: string | null;
  company?: string | null;
  jobPosition?: string | null;
  companyWebsite?: string | null;
  country?: string | null;
  message?: string | null;
  product?: (number | null) | Product;
  consentAt: string;
  consentText: string;
  routingProfile?: (number | null) | RoutingProfile;
  deliveryStatus?: ('manual-review' | 'pending' | 'delivered' | 'failed') | null;
  idempotencyKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'product-functions';
        value: number | ProductFunction;
      } | null)
    | ({
        relationTo: 'formulation-types';
        value: number | FormulationType;
      } | null)
    | ({
        relationTo: 'regulatory-labels';
        value: number | RegulatoryLabel;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'routing-profiles';
        value: number | RoutingProfile;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  sites?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  parentSite?: T;
  domain?: T;
  active?: T;
  market?: T;
  brandName?: T;
  parentLinkLabel?: T;
  navigation?:
    | T
    | {
        label?: T;
        path?: T;
        id?: T;
      };
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  site?: T;
  alt?: T;
  caption?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-functions_select".
 */
export interface ProductFunctionsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formulation-types_select".
 */
export interface FormulationTypesSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulatory-labels_select".
 */
export interface RegulatoryLabelsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  chemicalDescription?: T;
  description?: T;
  functions?: T;
  formulationTypes?: T;
  regulatoryLabels?: T;
  claimsReview?: T;
  casNumber?: T;
  manufacturingRegion?: T;
  resources?: T;
  image?: T;
  featured?: T;
  sourceNumber?: T;
  sourceRow?: T;
  sourceURL?: T;
  sourceDocument?: T;
  sourceCells?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  template?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        image?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  sourceURL?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  placement?: T;
  headline?: T;
  body?: T;
  desktopImage?: T;
  mobileImage?: T;
  ctaLabel?: T;
  ctaPath?: T;
  displayOrder?: T;
  sourceURL?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  description?: T;
  type?: T;
  availability?: T;
  placeholderLabel?: T;
  file?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routing-profiles_select".
 */
export interface RoutingProfilesSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  purpose?: T;
  mode?: T;
  connectorKey?: T;
  destinationTeam?: T;
  rules?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  purpose?: T;
  routingProfile?: T;
  consentLabel?: T;
  successMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  site?: T;
  form?: T;
  purpose?: T;
  email?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  jobPosition?: T;
  companyWebsite?: T;
  country?: T;
  message?: T;
  product?: T;
  consentAt?: T;
  consentText?: T;
  routingProfile?: T;
  deliveryStatus?: T;
  idempotencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}