// Preserve the live Worker's authentication compatibility and secure cookies.
import crypto from 'node:crypto';
// @ts-ignore Generated by the OpenNext build.
import worker from './.open-next/worker.js';
import { installCloudflarePbkdf2 } from './src/lib/cloudflare-pbkdf2';
import { securePayloadAuthCookie } from './src/lib/cloudflare-auth-cookie';
installCloudflarePbkdf2(crypto);
// @ts-ignore Generated by the OpenNext build.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js';
export default { ...worker, async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
  return securePayloadAuthCookie(await worker.fetch(request, env, ctx));
} };
